function(add_nfd SOURCE_DIR BINARY_DIR)
	set(nfd_source "${SOURCE_DIR}/src/nfd_common.c")
	if(WIN32)
		set(nfd_source ${nfd_source} "${SOURCE_DIR}/src/nfd_win.cpp")
	elseif(LINUX)
	endif()
	add_library(nfd STATIC EXCLUDE_FROM_ALL ${nfd_source})
	set_target_properties(nfd PROPERTIES C_STANDARD 99)
	set_target_properties(nfd PROPERTIES CXX_STANDARD 17)
	set_target_properties(nfd PROPERTIES ARCHIVE_OUTPUT_DIRECTORY ${BINARY_DIR})
	target_include_directories(nfd PUBLIC "${SOURCE_DIR}/src/include")
	if(MSVC)
		target_compile_definitions(nfd PRIVATE _CRT_SECURE_NO_WARNINGS)
		target_link_options(nfd PUBLIC /IGNORE:4099)
	endif()
endfunction()